DROP TABLE IF EXISTS account;
CREATE TABLE account(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(20) NOT NULL COMMENT '用户名',
  email VARCHAR(20) NOT NULL COMMENT 'email',
  hash_password VARCHAR(32) NOT NULL COMMENT 'hash密码',
  PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET =utf8;